name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: compile
      run: make
      
    - name: rtags
      run: make rtags
      
    - name: Run
      run: ./rtags data/gumichan01-eastern_wind.flac data/gumichan01-eastern_wind.m4a data/gumichan01-eastern_wind.mp3 data/gumichan01-eastern_wind.ogg data/gumichan01-eastern_wind.opus data/gumichan01-eastern_wind.wav
